name: CI/CD Pipeline
on: [push]

jobs:
  
  deploy-app:
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Pull the released image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/re21
      - name: export the Heroku token for login purpose
        run: export HEROKU_API_TOKEN=${{ secrets.HEROKU_API_KEY }}
      - name: connect to the Heroku registry
        run: heroku container:login
      - name: prepare the released image for deployment
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/re21 registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: push the image to heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: release the image into a new container
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        

